
export const Actions = {
    SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    GET_ME_REQUEST: 'GET_ME_REQUEST',
    GET_ME_SUCCESS: 'GET_ME_SUCCESS',

    ADD_FOLDER_REQUEST: 'ADD_FOLDER_REQUEST',
    ADD_FOLDER_SUCCESS: 'ADD_FOLDER_SUCCESS',
    GET_FOLDER_REQUEST:'GET_FOLDER_REQUEST',
    GET_FOLDER_SUCCESS:'GET_FOLDER_SUCCESS',
    RENAME_FOLDER_REQUEST:'RENAME_FOLDER_REQUEST',
    RENAME_FOLDER_SUCCESS:'RENAME_FOLDER_SUCCESS',
    DELETE_FOLDER_REQUEST:'DELETE_FOLDER_REQUEST',
    DELETE_FOLDER_SUCCESS:'DELETE_FOLDER_SUCCESS',

    CREATE_BOOKMARK_REQUEST:'CREATE_BOOKMARK_REQUEST',
    CREATE_BOOKMARK_SUCCESS:'CREATE_BOOKMARK_SUCCESS',
    GET_BOOKMARK_REQUEST:'GET_BOOKMARK_REQUEST',
    GET_BOOKMARK_SUCCESS:'GET_BOOKMARK_SUCCESS',
    DELETE_BOOKMARK_REQUEST:'DELETE_BOOKMARK_REQUEST',
    DELETE_BOOKMARK_SUCCESS:'DELETE_BOOKMARK_SUCCESS',
    MOVE_BOOKMARK_REQUEST:'MOVE_BOOKMARK_REQUEST',
    MOVE_BOOKMARK_SUCCESS:'MOVE_BOOKMARK_SUCCESS',

    ADD_FAVOUITE_BOOKMARK:'ADD_FAVOUITE_BOOKMARK',
    REMOVE_FAVOUITE_BOOKMARK:'REMOVE_FAVOUITE_BOOKMARK',
    TOGGLE_FAVOURITE_BOOKMARK_REQUEST:'TOGGLE_FAVOURITE_BOOKMARK_REQUEST',
    TOGGLE_FAVOURITE_BOOKMARK_SUCCESS:'TOGGLE_FAVOURITE_BOOKMARK_SUCCESS',

}