export const Actions = {
    SIGN_UP: 'SIGN_UP'
}

export const AsyncActions = {
    GITHUB_USER_DATA_REQUEST: "GITHUB_USER_DATA_REQUEST",
    GITHUB_USER_DATA_SUCCESS: "GITHUB_USER_DATA_SUCCESS",
    GITHUB_USER_DATA_FAILURE: "GITHUB_USER_DATA_FAILURE"
}