export const Actions = {
    SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_REQUEST',
    ADD_FOLDER_REQUEST: 'ADD_FOLDER_REQUEST',
    ADD_FOLDER_SUCCESS: 'ADD_FOLDER_SUCCESS',
    GET_FOLDER_REQUEST:'GET_FOLDER_REQUEST',
    GET_FOLDER_SUCCESS:'GET_FOLDER_SUCCESS',
}

